# Appveyor: for producing and deploying Windows builds
#------------------------------------------------------

version: 0.1.{build}

# Test against this version of Node.js
environment:
  nodejs_version: "6.2.1"

platform:
  - x64

# fetch repository as zip archive
shallow_clone: true

# skip mapeo-vX.Y.Z tags; we already know they build, since they're created
# as a result of a deployment completing
branches:
  except:
    - /mapeo-v.*/

artifacts:
  - path: '**\*.nupkg'
    name: nupkg
  - path: '**\InstallarMapeo.exe'
    name: exe

cache:
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version x64
  - npm install -g npm@latest
  - npm install

build_script:
  - if not exist "%USERPROFILE%\.electron" md "%USERPROFILE%\.electron"
  - npm config set msvs_version 2015 --global
  - node --version
  - npm --version
  - npm run build
  - npm run rebuild-leveldb
  - npm run package-win
  - npm run installer-win

test: off

deploy:
  release: mapeo-v$(appveyor_build_version)  # also the name of the tag that gets created
  provider: GitHub
  auth_token:
    secure: Do48zAyJyqq3Cqu0JLYy/ayhLbNvvDt+j/yZPi6GMIn/dD0t5En/11JFOLMG9c13
  draft: false
  prerelease: false
  on:
    branch: /^v/                   # don't match "mapeo-*" tags, otherwise we'll get into a tag loop
    appveyor_repo_tag: true        # deploy on tag push only
